#!/bin/dash
# Description: bspwm configuration file
# Host: mlixa
# Maintainer: robiha <hallin.rle@gmail.com>
# Modified: 2017-11-12

# Various settings {{{1
GAP=3
#PANEL_HEIGHT=2
bspc config window_gap $GAP;
#bspc config top_padding $(($PANEL_HEIGHT-$GAP))
#bspc config left_padding -$GAP
#bspc config right_padding -$GAP
#bspc config bottom_padding -$GAP
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
bspc config single_monocle       false

# Color settings
bspc config border_width                  1
bspc config focused_border_color          "#1793D1"
bspc config normal_border_color           "#000000"
bspc config presel_feedback_color         "#8F3724"

bspc config focus_follows_pointer  true
#bspc config pointer_follows_focus true

# Settings for manual splitting.
bspc config split_ratio     0.52

# Create and name desktop for multiple monitors.
$HOME/.config/bspwm/workspaces_multimonitor.sh &

# Rules {{{1

# Autostart {{{1
sxhkd &
compton &
xfsettingsd &
xfce4-power-manager &
xfce4-panel -d &
xfce4-clipman &
msm-notifier &
nm-applet &
pa-applet &
light-locker &
pamac-tray &
redshift-gtk &
megasync &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# vim: fdm=marker
